(function(name,data){
 if(typeof onTileMapLoaded === 'undefined') {
  if(typeof TileMaps === 'undefined') TileMaps = {};
  TileMaps[name] = data;
 } else {
  onTileMapLoaded(name,data);
 }
 if(typeof module === 'object' && module && module.exports) {
  module.exports = data;
 }})("iso-dungeon",
{ "backgroundcolor":"#323232",
 "height":10,
 "layers":[
        {
         "compression":"zlib",
         "data":"eJxjZGBgYARiVigNwugAlzgHELNDMbo6RjTMhianiUUNshi6e9DVYsP41DEgmY8NcGHxLzZsjWQGshtZcajnxOI3NSBWB2INLG4HAAEPAdM=",
         "encoding":"base64",
         "height":10,
         "name":"Floor",
         "opacity":1,
         "type":"tilelayer",
         "visible":true,
         "width":10,
         "x":0,
         "y":0
        }, 
        {
         "compression":"zlib",
         "data":"eJxjYWBgYAJifigNwuiABYi1sIijA2Yg1kHSAzKLF0leCEkdM5TNQ4SZICBIQJ0AlObGIqeHxTxCQACJLccA8QvIT7JALEOGecSqAwBWvwGB",
         "encoding":"base64",
         "height":10,
         "name":"Walls",
         "opacity":1,
         "type":"tilelayer",
         "visible":true,
         "width":10,
         "x":0,
         "y":0
        }, 
        {
         "compression":"zlib",
         "data":"eJxjYEAFhkCsAsWqSGLEAC00vhgQi2JRp0PAHH0c4hJQLE6ke0BAiQS1uIA8lFbEIW8ApXG5mxBQgNJ6QAwAhQIC1g==",
         "encoding":"base64",
         "height":10,
         "name":"Objects",
         "opacity":1,
         "type":"tilelayer",
         "visible":true,
         "width":10,
         "x":0,
         "y":0
        }, 
        {
         "compression":"zlib",
         "data":"eJxjYKANkAZiYSge7oCafgQAVYgAVQ==",
         "encoding":"base64",
         "height":10,
         "name":"Wood",
         "opacity":1,
         "type":"tilelayer",
         "visible":true,
         "width":10,
         "x":0,
         "y":0
        }, 
        {
         "compression":"zlib",
         "data":"eJxjYCAesAOxCBBzkKAHBHRJVD+SAQBmaABR",
         "encoding":"base64",
         "height":10,
         "name":"Second",
         "opacity":1,
         "type":"tilelayer",
         "visible":false,
         "width":10,
         "x":0,
         "y":0
        }],
 "nextobjectid":1,
 "orientation":"isometric",
 "renderorder":"right-down",
 "tiledversion":"1.0.1",
 "tileheight":149,
 "tilesets":[
        {
         "columns":0,
         "firstgid":1,
         "margin":0,
         "name":"Sample",
         "spacing":0,
         "tilecount":49,
         "tileheight":512,
         "tiles":
            {
             "0":
                {
                 "image":"..\/..\/..\/..\/Downloads\/kenney-isometric-dungeon-tiles\/Isometric\/stone_E.png",
                 "imageheight":512,
                 "imagewidth":256
                },
             "1":
                {
                 "image":"..\/..\/..\/..\/Downloads\/kenney-isometric-dungeon-tiles\/Isometric\/stoneWall_N.png",
                 "imageheight":512,
                 "imagewidth":256
                },
             "10":
                {
                 "image":"..\/..\/..\/..\/Downloads\/kenney-isometric-dungeon-tiles\/Isometric\/stoneWallCorner_W.png",
                 "imageheight":512,
                 "imagewidth":256
                },
             "11":
                {
                 "image":"..\/..\/..\/..\/Downloads\/kenney-isometric-dungeon-tiles\/Isometric\/stoneWallArchway_W.png",
                 "imageheight":512,
                 "imagewidth":256
                },
             "12":
                {
                 "image":"..\/..\/..\/..\/Downloads\/kenney-isometric-dungeon-tiles\/Isometric\/stoneWallBrokenRight_N.png",
                 "imageheight":512,
                 "imagewidth":256
                },
             "13":
                {
                 "image":"..\/..\/..\/..\/Downloads\/kenney-isometric-dungeon-tiles\/Isometric\/stoneWallDoorClosed_N.png",
                 "imageheight":512,
                 "imagewidth":256
                },
             "14":
                {
                 "image":"..\/..\/..\/..\/Downloads\/kenney-isometric-dungeon-tiles\/Isometric\/stoneWallHole_N.png",
                 "imageheight":512,
                 "imagewidth":256
                },
             "15":
                {
                 "image":"..\/..\/..\/..\/Downloads\/kenney-isometric-dungeon-tiles\/Isometric\/stoneWallGateBars_W.png",
                 "imageheight":512,
                 "imagewidth":256
                },
             "16":
                {
                 "image":"..\/..\/..\/..\/Downloads\/kenney-isometric-dungeon-tiles\/Isometric\/stoneWallBroken_W.png",
                 "imageheight":512,
                 "imagewidth":256
                },
             "17":
                {
                 "image":"..\/..\/..\/..\/Downloads\/kenney-isometric-dungeon-tiles\/Isometric\/stoneColumn_E.png",
                 "imageheight":512,
                 "imagewidth":256
                },
             "18":
                {
                 "image":"..\/..\/..\/..\/Downloads\/kenney-isometric-dungeon-tiles\/Isometric\/woodenSupportsBlock_E.png",
                 "imageheight":512,
                 "imagewidth":256
                },
             "19":
                {
                 "image":"..\/..\/..\/..\/Downloads\/kenney-isometric-dungeon-tiles\/Isometric\/planksHole_E.png",
                 "imageheight":512,
                 "imagewidth":256
                },
             "2":
                {
                 "image":"..\/..\/..\/..\/Downloads\/kenney-isometric-dungeon-tiles\/Isometric\/stoneWall_W.png",
                 "imageheight":512,
                 "imagewidth":256
                },
             "20":
                {
                 "image":"..\/..\/..\/..\/Downloads\/kenney-isometric-dungeon-tiles\/Isometric\/barrelsStacked_N.png",
                 "imageheight":512,
                 "imagewidth":256
                },
             "21":
                {
                 "image":"..\/..\/..\/..\/Downloads\/kenney-isometric-dungeon-tiles\/Isometric\/barrels_N.png",
                 "imageheight":512,
                 "imagewidth":256
                },
             "22":
                {
                 "image":"..\/..\/..\/..\/Downloads\/kenney-isometric-dungeon-tiles\/Isometric\/tableChairsBroken_W.png",
                 "imageheight":512,
                 "imagewidth":256
                },
             "23":
                {
                 "image":"..\/..\/..\/..\/Downloads\/kenney-isometric-dungeon-tiles\/Isometric\/tableShortChairs_S.png",
                 "imageheight":512,
                 "imagewidth":256
                },
             "24":
                {
                 "image":"..\/..\/..\/..\/Downloads\/kenney-isometric-dungeon-tiles\/Isometric\/tableShortChairs_W.png",
                 "imageheight":512,
                 "imagewidth":256
                },
             "25":
                {
                 "image":"..\/..\/..\/..\/Downloads\/kenney-isometric-dungeon-tiles\/Isometric\/woodenSupportsBeam_S.png",
                 "imageheight":512,
                 "imagewidth":256
                },
             "26":
                {
                 "image":"..\/..\/..\/..\/Downloads\/kenney-isometric-dungeon-tiles\/Isometric\/woodenSupportsBeam_E.png",
                 "imageheight":512,
                 "imagewidth":256
                },
             "27":
                {
                 "image":"..\/..\/..\/..\/Downloads\/kenney-isometric-dungeon-tiles\/Isometric\/stoneWallCorner_E.png",
                 "imageheight":512,
                 "imagewidth":256
                },
             "28":
                {
                 "image":"..\/..\/..\/..\/Downloads\/kenney-isometric-dungeon-tiles\/Isometric\/stoneWallGate_N.png",
                 "imageheight":512,
                 "imagewidth":256
                },
             "29":
                {
                 "image":"..\/..\/..\/..\/Downloads\/kenney-isometric-dungeon-tiles\/Isometric\/stoneWallAgedLeft_N.png",
                 "imageheight":512,
                 "imagewidth":256
                },
             "3":
                {
                 "image":"..\/..\/..\/..\/Downloads\/kenney-isometric-dungeon-tiles\/Isometric\/stoneWallCorner_N.png",
                 "imageheight":512,
                 "imagewidth":256
                },
             "30":
                {
                 "image":"..\/..\/..\/..\/Downloads\/kenney-isometric-dungeon-tiles\/Isometric\/woodenCrate_E.png",
                 "imageheight":512,
                 "imagewidth":256
                },
             "31":
                {
                 "image":"..\/..\/..\/..\/Downloads\/kenney-isometric-dungeon-tiles\/Isometric\/woodenCrates_W.png",
                 "imageheight":512,
                 "imagewidth":256
                },
             "32":
                {
                 "image":"..\/..\/..\/..\/Downloads\/kenney-isometric-dungeon-tiles\/Isometric\/woodenPile_N.png",
                 "imageheight":512,
                 "imagewidth":256
                },
             "33":
                {
                 "image":"..\/..\/..\/..\/Downloads\/kenney-isometric-dungeon-tiles\/Isometric\/barrel_S.png",
                 "imageheight":512,
                 "imagewidth":256
                },
             "34":
                {
                 "image":"..\/..\/..\/..\/Downloads\/kenney-isometric-dungeon-tiles\/Isometric\/stairs_E.png",
                 "imageheight":512,
                 "imagewidth":256
                },
             "35":
                {
                 "image":"..\/..\/..\/..\/Downloads\/kenney-isometric-dungeon-tiles\/Isometric\/stairs_N.png",
                 "imageheight":512,
                 "imagewidth":256
                },
             "36":
                {
                 "image":"..\/..\/..\/..\/Downloads\/kenney-isometric-dungeon-tiles\/Isometric\/stairsAged_N.png",
                 "imageheight":512,
                 "imagewidth":256
                },
             "37":
                {
                 "image":"..\/..\/..\/..\/Downloads\/kenney-isometric-dungeon-tiles\/Isometric\/dirt_E.png",
                 "imageheight":512,
                 "imagewidth":256
                },
             "38":
                {
                 "image":"..\/..\/..\/..\/Downloads\/kenney-isometric-dungeon-tiles\/Isometric\/dirtTiles_E.png",
                 "imageheight":512,
                 "imagewidth":256
                },
             "39":
                {
                 "image":"..\/..\/..\/..\/Downloads\/kenney-isometric-dungeon-tiles\/Isometric\/stoneSideUneven_N.png",
                 "imageheight":512,
                 "imagewidth":256
                },
             "4":
                {
                 "image":"..\/..\/..\/..\/Downloads\/kenney-isometric-dungeon-tiles\/Isometric\/stoneMissingTiles_E.png",
                 "imageheight":512,
                 "imagewidth":256
                },
             "40":
                {
                 "image":"..\/..\/..\/..\/Downloads\/kenney-isometric-dungeon-tiles\/Isometric\/stoneUneven_E.png",
                 "imageheight":512,
                 "imagewidth":256
                },
             "41":
                {
                 "image":"..\/..\/..\/..\/Downloads\/kenney-isometric-dungeon-tiles\/Isometric\/stoneWallColumnIn_W.png",
                 "imageheight":512,
                 "imagewidth":256
                },
             "42":
                {
                 "image":"..\/..\/..\/..\/Downloads\/kenney-isometric-dungeon-tiles\/Isometric\/stoneWallWindow_W.png",
                 "imageheight":512,
                 "imagewidth":256
                },
             "43":
                {
                 "image":"..\/..\/..\/..\/Downloads\/kenney-isometric-dungeon-tiles\/Isometric\/stoneWallWindowBars_W.png",
                 "imageheight":512,
                 "imagewidth":256
                },
             "44":
                {
                 "image":"..\/..\/..\/..\/Downloads\/kenney-isometric-dungeon-tiles\/Isometric\/stairsSpiral_W.png",
                 "imageheight":512,
                 "imagewidth":256
                },
             "45":
                {
                 "image":"..\/..\/..\/..\/Downloads\/kenney-isometric-dungeon-tiles\/Isometric\/stoneColumnWood_S.png",
                 "imageheight":512,
                 "imagewidth":256
                },
             "46":
                {
                 "image":"..\/..\/..\/..\/Downloads\/kenney-isometric-dungeon-tiles\/Isometric\/tableRoundChairs_E.png",
                 "imageheight":512,
                 "imagewidth":256
                },
             "47":
                {
                 "image":"..\/..\/..\/..\/Downloads\/kenney-isometric-dungeon-tiles\/Isometric\/chestClosed_W.png",
                 "imageheight":512,
                 "imagewidth":256
                },
             "48":
                {
                 "image":"..\/..\/..\/..\/Downloads\/kenney-isometric-dungeon-tiles\/Isometric\/chestOpen_N.png",
                 "imageheight":512,
                 "imagewidth":256
                },
             "5":
                {
                 "image":"..\/..\/..\/..\/Downloads\/kenney-isometric-dungeon-tiles\/Isometric\/stoneTile_E.png",
                 "imageheight":512,
                 "imagewidth":256
                },
             "6":
                {
                 "image":"..\/..\/..\/..\/Downloads\/kenney-isometric-dungeon-tiles\/Isometric\/planks_E.png",
                 "imageheight":512,
                 "imagewidth":256
                },
             "7":
                {
                 "image":"..\/..\/..\/..\/Downloads\/kenney-isometric-dungeon-tiles\/Isometric\/planksBroken_E.png",
                 "imageheight":512,
                 "imagewidth":256
                },
             "8":
                {
                 "image":"..\/..\/..\/..\/Downloads\/kenney-isometric-dungeon-tiles\/Isometric\/bridge_E.png",
                 "imageheight":512,
                 "imagewidth":256
                },
             "9":
                {
                 "image":"..\/..\/..\/..\/Downloads\/kenney-isometric-dungeon-tiles\/Isometric\/bridgeBroken_N.png",
                 "imageheight":512,
                 "imagewidth":256
                }
            },
         "tilewidth":256
        }, 
        {
         "firstgid":50,
         "source":"..\/..\/..\/..\/Desktop\/isot.tsx"
        }],
 "tilewidth":256,
 "type":"map",
 "version":1,
 "width":10
});